name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
      - uses: actions/checkout@v2
        with:
            ref: gh-pages
      - run: |
          echo devitt.dev > CNAME
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "CNAME Update"
          git push
